### ISSUE TITLE
[Feat] forward files to different channels or groups

### ISSUE THREAD

**Issue by garyvalue** [1368129224/tgbot-for-tdl#2]
### Proposal
Can you add a forwarding function to forward files to different channels or groups/sessions according to the selected tag?
 Will this be considered?

### Workarounds

done

**Comment by 1368129224** [comment]
Sorry, the original intention of this project was to make it easier to download files using tdl, so this feature will not be considered for implementation for now, also this feature has nothing to do with [tdl](https://github.com/iyear/tdl), it can be implemented only through [python-telegram-bot](https://github.com/python-telegram-bot/python-telegram-bot) or any other telegram bot project.
